spring.datasource.url=jdbc:postgresql://localhost:5432/ecomm_db
spring.datasource.username=admin
spring.datasource.password=secure_postgres_pass_123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File storage config
project.image.path=/Users/marcus/Developer/images/